aliases: []
creation_timestamp: 1748805889780
current_stage: None
description: ''
last_updated_timestamp: 1748805889780
name: gesture-model
run_id: d1dd4dde44a54f3c8473b907532c1201
run_link: ''
source: file:///C:/Users/fayro/Downloads/mlops_project/hand-gesture-research/notebooks/mlruns/507331089791027613/d1dd4dde44a54f3c8473b907532c1201/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/fayro/Downloads/mlops_project/hand-gesture-research/notebooks/mlruns/507331089791027613/d1dd4dde44a54f3c8473b907532c1201/artifacts/model
user_id: null
version: 1
